performance: # Performance related settings, change with caution
  # X/Z divisions: generally best practice is to try to go for multiples of 16 if possible. Optimally this would be some
  # reasonable lower bound: you want to cover the smallest area possible while minimizing the number of min-divisions
  # needed to cover an entire region
  min-division-x: 96
  min-division-z: 96
  # The maximum number of ticks an effect can be delayed from ticking for performance: note that this does not affect
  # actual scheduling, which is exact
  effect-tick-max-delay: 5
  # The maximum amount of ticks to defer a regional check for blcok consistancy (i.e. that block requirements are still
  # met) after a block is broken. The higher, the better, albeit higher also means a greater delay before upkeep attempts
  consistency-check-block-max-delay: 100

protection:
  protect-flint-and-steel: false # Affected by the INTERACT protection
  protect-interact: # Affected by the INTERACT protection
  - ACACIA_DOOR
  - ACACIA_FENCE_GATE
  - BIRCH_DOOR
  - BIRCH_FENCE_GATE
  - DARK_OAK_DOOR
  - DARK_OAK_FENCE_GATE
  - DRAGON_EGG
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - FENCE_GATE
  - JUNGLE_DOOR
  - JUNGLE_FENCE_GATE
  - LEVER
  - NOTE_BLOCK
  - PAINTING
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - SIGN
  - SIGN_POST
  - SPRUCE_DOOR
  - SPRUCE_FENCE_GATE
  - STONE_BUTTON
  - TRAP_DOOR
  - WALL_SIGN
  - WOOD_BUTTON
  - WOODEN_DOOR
  protect-access: # Protected by the ACCESS Protection
  - ANVIL
  - BREWING_STAND
  - CHEST
  - DISPENSER
  - DROPPER
  - ENCHANTMENT_TABLE
  - ENDER_CHEST
  - ENDER_PORTAL_FRAME
  - FURNACE
  - BURNING_FURNACE
  - HOPPER
  - ITEM_FRAME
  - JUKEBOX
  - TRAPPED_CHEST
  - WORKBENCH
region-relations:
  minimum-declarable-tier: 2      # Minimum regional tier to have relationships with other regions, cannot be disabled
  maximum-tier-difference: -1     # Maximum difference of two regional tiers to declare some relationship, -1 to disable
  relation-change-delay: 86400000 # Time before a relation change is put into effect, can be cancelled before then
